# Generated by Django 2.2.5 on 2019-11-19 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_Name', models.CharField(max_length=60, verbose_name='Name')),
                ('project_Description', models.TextField(max_length=300, verbose_name='Description')),
                ('project_MaxCapacity', models.PositiveIntegerField(default=10, verbose_name='Maximum Capacity')),
                ('project_SpaceTaken', models.PositiveIntegerField(default=1, verbose_name='Space Taken')),
                ('project_SpaceAvailable', models.PositiveIntegerField(blank=True)),
                ('project_Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Involved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_involved_accepted', models.BooleanField(default=False)),
                ('project_involved_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Project')),
                ('project_involved_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
            options={
                'unique_together': {('project_involved_username', 'project_involved_id')},
            },
        ),
    ]
