# Generated by Django 2.2.5 on 2019-11-05 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
    ]
