# Generated by Django 2.2.5 on 2019-11-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_project_project_involved'),
    ]

    operations = [
    ]
