# Generated by Django 2.2.5 on 2019-11-05 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191105_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userPassword',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_Email',
            field=models.CharField(default='email@email.com', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_PhoneNo',
            field=models.CharField(default='111-222-3333', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_firstName',
            field=models.CharField(default='First Name', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_lastName',
            field=models.CharField(default='Last Name', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_password',
            field=models.CharField(default='Password', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_username',
            field=models.CharField(default='Username', max_length=60, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_Name', models.CharField(max_length=60)),
                ('project_Description', models.CharField(max_length=300)),
                ('project_MaxCapacity', models.CharField(max_length=20)),
                ('project_SpaceTaken', models.CharField(max_length=20)),
                ('project_SpaceAvailable', models.CharField(max_length=10)),
                ('project_Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Involved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Project')),
            ],
            options={
                'unique_together': {('profile_username', 'project_id')},
            },
        ),
    ]
