# Generated by Django 2.2.5 on 2019-11-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191105_0058'),
    ]

    operations = [
    ]
