# Generated by Django 2.2.5 on 2019-11-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191105_0101'),
    ]

    operations = [
    ]
