# Generated by Django 2.2.5 on 2019-11-05 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191105_0104'),
    ]

    operations = [
    ]
