# Generated by Django 2.2.5 on 2019-11-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20191105_0109'),
    ]

    operations = [
    ]
