# Generated by Django 2.2.5 on 2019-11-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20191105_0314'),
    ]

    operations = [
    ]
