# Generated by Django 2.2.5 on 2019-11-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20191105_1846'),
    ]

    operations = [
    ]
