# Generated by Django 2.2.5 on 2019-11-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20191105_1846'),
    ]

    operations = [
    ]
