# Generated by Django 2.2.5 on 2019-11-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20191105_2141'),
    ]

    operations = [
    ]
