# Generated by Django 2.2.5 on 2019-11-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20191106_2209'),
    ]

    operations = [
    ]
