# Generated by Django 2.2.5 on 2019-11-06 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20191106_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_Email',
            field=models.EmailField(max_length=20, verbose_name='E-mail Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_PhoneNo',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_firstName',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_lastName',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_password',
            field=models.CharField(max_length=60, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="1. Cannot start or have  '_' or '.' together, only be used once \n 2. Length must be between 8 to 20 characters. \n 3. Only contains alphanumeric characters, '.' and '_' ", regex='^[a-zA-Z0-9]([._](?![._])|[a-zA-Z0-9]){6,18}[a-zA-Z0-9]$')], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_Description',
            field=models.TextField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_MaxCapacity',
            field=models.PositiveIntegerField(default=10, verbose_name='Maximum Capacity'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_Name',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_SpaceAvailable',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_SpaceTaken',
            field=models.PositiveIntegerField(default=1, verbose_name='Space Taken'),
        ),
        migrations.AlterField(
            model_name='project_involved',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
