# Generated by Django 2.2.5 on 2019-11-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20191106_2218'),
    ]

    operations = [
    ]
