# Generated by Django 2.2.5 on 2019-11-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20191107_0155'),
    ]

    operations = [
    ]
