# Generated by Django 2.2.5 on 2019-11-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20191115_1130'),
    ]

    operations = [
    ]
