# Generated by Django 2.2.5 on 2019-11-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20191117_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_involved',
            name='project_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
