# Generated by Django 2.2.5 on 2019-11-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_project_involved_project_accepted'),
    ]

    operations = [
    ]
