# Generated by Django 2.2.5 on 2019-11-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20191118_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_involved',
            old_name='project_id',
            new_name='project_involved_id',
        ),
        migrations.RenameField(
            model_name='project_involved',
            old_name='profile_username',
            new_name='project_involved_username',
        ),
        migrations.AlterUniqueTogether(
            name='project_involved',
            unique_together={('project_involved_username', 'project_involved_id')},
        ),
    ]
