# Generated by Django 2.2.5 on 2019-11-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20191118_2106'),
    ]

    operations = [
    ]
