# Generated by Django 2.2.5 on 2019-11-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20191119_1237'),
    ]

    operations = [
    ]
