# Generated by Django 2.2.5 on 2019-11-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20191119_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_involved',
            old_name='project_accepted',
            new_name='project_involved_accepted',
        ),
    ]
